import type { LessonContent } from '@/types/content';
import type { TopicId } from '@/types/curriculum';

import { lesson as integersAddSub } from './numbers/num-integers-add-sub.lesson';
import { lesson as integersMulDiv } from './numbers/num-integers-mul-div.lesson';
import { lesson as fractionsCompare } from './numbers/num-fractions-compare.lesson';
import { lesson as fractionsAddSub } from './numbers/num-fractions-add-sub.lesson';
import { lesson as percentBasics } from './numbers/num-percent-basics.lesson';
import { lesson as fractionsMulDiv } from './numbers/num-fractions-mul-div.lesson';
import { lesson as squareRoots } from './numbers/num-square-roots.lesson';
import { lesson as expressionsSubstitute } from './algebra/alg-expressions-substitute.lesson';
import { lesson as collectLikeTerms } from './algebra/alg-collect-like-terms.lesson';
import { lesson as coordinatePlane } from './functions/fun-coordinate-plane.lesson';
import { lesson as distributive } from './algebra/alg-distributive.lesson';
import { lesson as linearEqBasic } from './algebra/alg-linear-eq-basic.lesson';
import { lesson as areaPerimeter } from './geometry/geo-area-perimeter.lesson';
import { lesson as pythagoras } from './geometry/geo-pythagoras.lesson';
import { lesson as meanMedianMode } from './stats/sta-mean-median-mode.lesson';
import { lesson as decimalsOps } from './numbers/num-decimals-ops.lesson';
import { lesson as fractionDecimalPercent } from './numbers/num-fraction-decimal-percent.lesson';
import { lesson as powersLaws } from './numbers/num-powers-laws.lesson';
import { lesson as wordProblemsIntro } from './algebra/alg-word-problems-intro.lesson';
import { lesson as multiplyBrackets } from './algebra/alg-multiply-brackets.lesson';
import { lesson as linearFunction } from './functions/fun-linear-function.lesson';

/**
 * Hand-written teaching content. Imported explicitly rather than globbed, so a
 * renamed file fails to compile instead of silently vanishing from the app.
 * Topics without an entry here get their lesson generated by the tutor on first
 * visit and cached on the device.
 */
const AUTHORED: readonly LessonContent[] = [
  integersAddSub,
  integersMulDiv,
  fractionsCompare,
  fractionsAddSub,
  percentBasics,
  fractionsMulDiv,
  squareRoots,
  expressionsSubstitute,
  collectLikeTerms,
  coordinatePlane,
  distributive,
  linearEqBasic,
  areaPerimeter,
  pythagoras,
  meanMedianMode,
  decimalsOps,
  fractionDecimalPercent,
  powersLaws,
  wordProblemsIntro,
  multiplyBrackets,
  linearFunction,
];

export const LESSONS: ReadonlyMap<TopicId, LessonContent> = new Map(
  AUTHORED.map((l) => [l.topicId, l]),
);

export const getAuthoredLesson = (topicId: TopicId): LessonContent | undefined =>
  LESSONS.get(topicId);

export const hasAuthoredLesson = (topicId: TopicId): boolean => LESSONS.has(topicId);

export const authoredLessons = (): readonly LessonContent[] => AUTHORED;
